[package]
name = "fire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib-ffi = "4"
tinyrand = "0.5.0"
